{
    "parserOptions": { "ecmaVersion": 6, "sourceType": "module" },
    "env": { "es6": true, "commonjs": true, "mocha": true },
    "extends": "htmlacademy/es6",
    rules: { "indent": ["error", "tab"] },
}
